const fakeVideos = [
  {
    id: 1,
    title: '10 Tips You NEED to Know Before Starting',
    channel: 'TechGuru',
    avatar: 'T',
    color: '#e53935',
    gradient: 'linear-gradient(135deg, #e53935, #ff7043)',
    thumbText: '10 Tips You\nNEED to Know',
    thumbTextSmall: '10 Tips',
    duration: '15:23',
    views: '1.2M views',
    age: '3 days ago',
  },
  {
    id: 2,
    title: 'How I Made $10K/Month With No Experience',
    channel: 'HustleHub',
    avatar: 'H',
    color: '#1e88e5',
    gradient: 'linear-gradient(135deg, #1e88e5, #42a5f5)',
    thumbText: 'How I Made\n$10K/Month',
    thumbTextSmall: '$10K/Month',
    duration: '22:07',
    views: '845K views',
    age: '1 week ago',
  },
  {
    id: 3,
    title: 'The TRUTH About AI Nobody Tells You',
    channel: 'AI Insider',
    avatar: 'A',
    color: '#7b1fa2',
    gradient: 'linear-gradient(135deg, #7b1fa2, #ce93d8)',
    thumbText: 'The TRUTH\nAbout AI',
    thumbTextSmall: 'AI Truth',
    duration: '8:41',
    views: '2.1M views',
    age: '5 days ago',
  },
  {
    id: 4,
    title: 'I Survived 100 Days in Hardcore Minecraft',
    channel: 'MCAdventures',
    avatar: 'M',
    color: '#2e7d32',
    gradient: 'linear-gradient(135deg, #2e7d32, #66bb6a)',
    thumbText: 'I Survived\n100 Days',
    thumbTextSmall: '100 Days',
    duration: '34:12',
    views: '5.6M views',
    age: '2 weeks ago',
  },
  {
    id: 5,
    title: "BEST Budget Phone 2026 - Don't Waste Money!",
    channel: 'PhoneReviews',
    avatar: 'P',
    color: '#ef6c00',
    gradient: 'linear-gradient(135deg, #ef6c00, #ffb74d)',
    thumbText: 'BEST Budget\nPhone 2026',
    thumbTextSmall: 'Budget Phone',
    duration: '11:55',
    views: '920K views',
    age: '4 days ago',
  },
  {
    id: 6,
    title: "World's Most DANGEROUS Roads You Won't Believe",
    channel: 'DareDevil',
    avatar: 'D',
    color: '#c62828',
    gradient: 'linear-gradient(135deg, #c62828, #ef5350)',
    thumbText: "World's Most\nDANGEROUS",
    thumbTextSmall: 'DANGEROUS',
    duration: '18:30',
    views: '3.4M views',
    age: '1 month ago',
  },
  {
    id: 7,
    title: 'Learn CSS Grid in 20 Minutes - Complete Guide',
    channel: 'CodeSimple',
    avatar: 'C',
    color: '#00838f',
    gradient: 'linear-gradient(135deg, #00838f, #4dd0e1)',
    thumbText: 'Learn CSS\nin 20 Min',
    thumbTextSmall: 'CSS Grid',
    duration: '20:15',
    views: '1.8M views',
    age: '6 months ago',
  },
]

export default fakeVideos
